# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      The Network Security Policies (NSP) for the associated
      Hipster Store microservice demo application.
  name: hipster-store-demo
objects:
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: ExternalNetwork
  metadata:
    # This metadata field will be what you see with the command
    # `oc get externalnetwork` or `kubctl get externalnetwork`.
    name: all-things-external
  spec:
    # This name will be used internally by Aporeto; it should match
    # the `name` field in metadata above.
    description: |
      specify a custom external network that can be
      referenced by name.
    entries:
    - 0.0.0.0/0
    protocols:
    - tcp
    - udp
    ports:
    - "80"
    - "443"
    - "53"
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: to-external-dns
    labels:
      app: hipster-store
  spec:
    description: |
      allow the front end and checkout service to access
      external DNS services
    source:
      - - $namespace=${NAMESPACE}
        - 'role=frontend'
      - - $namespace=${NAMESPACE}
        - 'role=checkoutservice'
    destination:
      - - 'ext:name=all-things-external'
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-comms
    labels:
      app: hipster-store
  spec:
    description: |
      allow all pods in the namespace to talk to the
      k8s api
    source:
    - - '$namespace=${NAMESPACE}'
    destination:
    - - 'int:network=internal-cluster-api-endpoint'
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: frontend-to-int-services
    labels:
      app: hipster-store
  spec:
    description: |
      allow the frontend pod(s) only talk to the services
      it needs to.
    source:
    - - '$namespace=${NAMESPACE}'
      - 'role=frontend'
    destination:
    - - '$namespace=${NAMESPACE}'
      - 'role=adservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=checkoutservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=shippingservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=currencyservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=productcatalogservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=recommendationservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=cartservice'
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: checkoutservice-to-int-services
    labels:
      app: hipster-store
  spec:
    description: |
      allow the checkout service pod(s) to only talk to services
      it needs to.
    source:
    - - '$namespace=${NAMESPACE}'
      - 'role=checkoutservice'
    destination:
    - - '$namespace=${NAMESPACE}'
      - 'role=emailservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=paymentservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=shippingservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=currencyservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=productcatalogservice'
    - - '$namespace=${NAMESPACE}'
      - 'role=cartservice'
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: recommendationservice-to-int-services
    labels:
      app: hipster-store
  spec:
    description: |
      allow the recommendation service pod(s) to only talk to services
      it needs to.
    source:
    - - '$namespace=${NAMESPACE}'
      - 'role=recommendationservice'
    destination:
    - - '$namespace=${NAMESPACE}'
      - 'role=productcatalogservice'
- apiVersion: security.developer.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: cartservice-to-int-services
    labels:
      app: hipster-store
  spec:
    description: |
      allow the cart service pod(s) to only talk to services
      it needs to.
    source:
    - - '$namespace=${NAMESPACE}'
      - 'role=cartservice'
    destination:
    - - '$namespace=${NAMESPACE}'
      - 'role=redis-cart'
parameters:
- name: NAMESPACE
  description: |
    The the name of the namespace the policy is being
    deployed to.
  required: true